# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../InkscapeWorkspace/TheaterLogo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_input = QtWidgets.QPushButton(self.centralwidget)
        self.pb_input.setGeometry(QtCore.QRect(660, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_input.setFont(font)
        self.pb_input.setObjectName("pb_input")
        self.te_input = QtWidgets.QTextEdit(self.centralwidget)
        self.te_input.setGeometry(QtCore.QRect(30, 20, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_input.setFont(font)
        self.te_input.setObjectName("te_input")
        self.tb_anzahl = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_anzahl.setGeometry(QtCore.QRect(210, 200, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tb_anzahl.setFont(font)
        self.tb_anzahl.setObjectName("tb_anzahl")
        self.l_anzahl = QtWidgets.QLabel(self.centralwidget)
        self.l_anzahl.setGeometry(QtCore.QRect(30, 200, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_anzahl.sizePolicy().hasHeightForWidth())
        self.l_anzahl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_anzahl.setFont(font)
        self.l_anzahl.setObjectName("l_anzahl")
        self.te_leer = QtWidgets.QTextEdit(self.centralwidget)
        self.te_leer.setGeometry(QtCore.QRect(210, 260, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_leer.setFont(font)
        self.te_leer.setObjectName("te_leer")
        self.l_leer = QtWidgets.QLabel(self.centralwidget)
        self.l_leer.setGeometry(QtCore.QRect(30, 260, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_leer.setFont(font)
        self.l_leer.setObjectName("l_leer")
        self.l_bus = QtWidgets.QLabel(self.centralwidget)
        self.l_bus.setGeometry(QtCore.QRect(30, 320, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_bus.setFont(font)
        self.l_bus.setObjectName("l_bus")
        self.te_bus = QtWidgets.QTextEdit(self.centralwidget)
        self.te_bus.setGeometry(QtCore.QRect(210, 320, 121, 51))
        self.te_bus.setObjectName("te_bus")
        self.pb_start = QtWidgets.QPushButton(self.centralwidget)
        self.pb_start.setGeometry(QtCore.QRect(210, 380, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_start.setFont(font)
        self.pb_start.setObjectName("pb_start")
        self.te_output = QtWidgets.QTextEdit(self.centralwidget)
        self.te_output.setGeometry(QtCore.QRect(30, 120, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_output.setFont(font)
        self.te_output.setObjectName("te_output")
        self.pb_outline = QtWidgets.QPushButton(self.centralwidget)
        self.pb_outline.setGeometry(QtCore.QRect(660, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_outline.setFont(font)
        self.pb_outline.setObjectName("pb_outline")
        self.te_template = QtWidgets.QTextEdit(self.centralwidget)
        self.te_template.setGeometry(QtCore.QRect(30, 70, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_template.setFont(font)
        self.te_template.setObjectName("te_template")
        self.pb_template = QtWidgets.QPushButton(self.centralwidget)
        self.pb_template.setGeometry(QtCore.QRect(660, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_template.setFont(font)
        self.pb_template.setObjectName("pb_template")
        self.ticket_preview = QtWidgets.QLabel(self.centralwidget)
        self.ticket_preview.setGeometry(QtCore.QRect(420, 350, 461, 261))
        self.ticket_preview.setText("")
        self.ticket_preview.setPixmap(QtGui.QPixmap("../Theater/Ticket_Generator/input/ticketImage.png"))
        self.ticket_preview.setScaledContents(True)
        self.ticket_preview.setObjectName("ticket_preview")
        self.l_status = QtWidgets.QLabel(self.centralwidget)
        self.l_status.setGeometry(QtCore.QRect(30, 380, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_status.setFont(font)
        self.l_status.setObjectName("l_status")
        self.list_toEdit = QtWidgets.QListWidget(self.centralwidget)
        self.list_toEdit.setGeometry(QtCore.QRect(440, 210, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_toEdit.setFont(font)
        self.list_toEdit.setObjectName("list_toEdit")
        item = QtWidgets.QListWidgetItem()
        self.list_toEdit.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_toEdit.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_toEdit.addItem(item)
        self.pb_right = QtWidgets.QPushButton(self.centralwidget)
        self.pb_right.setGeometry(QtCore.QRect(690, 230, 31, 31))
        self.pb_right.setObjectName("pb_right")
        self.pb_left = QtWidgets.QPushButton(self.centralwidget)
        self.pb_left.setGeometry(QtCore.QRect(590, 230, 31, 31))
        self.pb_left.setObjectName("pb_left")
        self.pb_up = QtWidgets.QPushButton(self.centralwidget)
        self.pb_up.setGeometry(QtCore.QRect(640, 180, 31, 31))
        self.pb_up.setObjectName("pb_up")
        self.pb_down = QtWidgets.QPushButton(self.centralwidget)
        self.pb_down.setGeometry(QtCore.QRect(640, 280, 31, 31))
        self.pb_down.setObjectName("pb_down")
        self.te_x = QtWidgets.QTextEdit(self.centralwidget)
        self.te_x.setGeometry(QtCore.QRect(940, 200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_x.setFont(font)
        self.te_x.setObjectName("te_x")
        self.te_y = QtWidgets.QTextEdit(self.centralwidget)
        self.te_y.setGeometry(QtCore.QRect(940, 250, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_y.setFont(font)
        self.te_y.setObjectName("te_y")
        self.l_x = QtWidgets.QLabel(self.centralwidget)
        self.l_x.setGeometry(QtCore.QRect(790, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_x.setFont(font)
        self.l_x.setObjectName("l_x")
        self.l_y = QtWidgets.QLabel(self.centralwidget)
        self.l_y.setGeometry(QtCore.QRect(790, 250, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_y.setFont(font)
        self.l_y.setObjectName("l_y")
        self.te_step = QtWidgets.QTextEdit(self.centralwidget)
        self.te_step.setGeometry(QtCore.QRect(630, 220, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.te_step.setFont(font)
        self.te_step.setObjectName("te_step")
        self.pb_new_outline = QtWidgets.QPushButton(self.centralwidget)
        self.pb_new_outline.setGeometry(QtCore.QRect(770, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_new_outline.setFont(font)
        self.pb_new_outline.setObjectName("pb_new_outline")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.te_input, self.pb_input)
        MainWindow.setTabOrder(self.pb_input, self.te_output)
        MainWindow.setTabOrder(self.te_output, self.pb_outline)
        MainWindow.setTabOrder(self.pb_outline, self.tb_anzahl)
        MainWindow.setTabOrder(self.tb_anzahl, self.te_leer)
        MainWindow.setTabOrder(self.te_leer, self.te_bus)
        MainWindow.setTabOrder(self.te_bus, self.pb_start)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_input.setText(_translate("MainWindow", "Input"))
        self.te_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tb_anzahl.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.l_anzahl.setText(_translate("MainWindow", "Anzahl Tickets:"))
        self.te_leer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.l_leer.setText(_translate("MainWindow", "Leere Plätze:"))
        self.l_bus.setText(_translate("MainWindow", "Bus Plätze:"))
        self.te_bus.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">0</span></p></body></html>"))
        self.pb_start.setText(_translate("MainWindow", "Start"))
        self.te_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pb_outline.setText(_translate("MainWindow", "Outline"))
        self.te_template.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pb_template.setText(_translate("MainWindow", "Template"))
        self.l_status.setText(_translate("MainWindow", "-status-"))
        __sortingEnabled = self.list_toEdit.isSortingEnabled()
        self.list_toEdit.setSortingEnabled(False)
        item = self.list_toEdit.item(0)
        item.setText(_translate("MainWindow", "name"))
        item = self.list_toEdit.item(1)
        item.setText(_translate("MainWindow", "datum"))
        item = self.list_toEdit.item(2)
        item.setText(_translate("MainWindow", "platz"))
        self.list_toEdit.setSortingEnabled(__sortingEnabled)
        self.pb_right.setText(_translate("MainWindow", ">"))
        self.pb_left.setText(_translate("MainWindow", "<"))
        self.pb_up.setText(_translate("MainWindow", "^"))
        self.pb_down.setText(_translate("MainWindow", "|"))
        self.te_x.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p></body></html>"))
        self.te_y.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p></body></html>"))
        self.l_x.setText(_translate("MainWindow", "Nebeneinander"))
        self.l_y.setText(_translate("MainWindow", "Untereinander"))
        self.te_step.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p></body></html>"))
        self.pb_new_outline.setText(_translate("MainWindow", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
